# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
sudo: required

language: R
cache: packages
warnings_are_errors: false

services:
  - docker

before_install:
  - docker pull skvrnami/mordor-docker
  - docker ps
  - docker run -p 4000:80 skvrnami/mordor-docker

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov(coverage = covr::package_coverage())'
